Update service-portal-submission-approval.xml
output was misspelled causing the following error when manager approval

The "input" parameter of the "Manager Username from User Attribute" node could not be evaluated due to a NameError.

  PROBLEM:
  undefined local variable or method `outupt' within current binding.

  PARAMETER TEMPLATE:
  1: <%=
  2: output = "Default"
  3: attributes = JSON.parse(@results['Retrieve Created By User']['Attributes Map JSON'])
  4: if(attributes.has_key?('Manager') && !attributes['Manager'].empty?)
  5:   output = attributes['Manager'][0]
  6: end
  7: outupt%>